name: cfit
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0
  shimmer: ^2.0.0
  convex_bottom_bar: ^3.0.0
  bottom_bar: ^1.3.0+1
  top_snackbar_flutter: ^1.0.2
  mask_input_formatter: ^0.0.3
  dio: ^4.0.6
  flutter_blurhash: ^0.7.0
  provider: ^6.0.2
  fluttertoast: ^8.0.9
  badges: ^2.0.2
  local_auth: ^2.0.1
  path_provider: ^2.0.9
  qr_flutter: ^4.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/google_logo.png
    - assets/language/
    - assets/icons/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Regular.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Bold.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Semibold.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Medium.ttf
flutter_icons:
  ios: true
  android: true
  windows: true
  web: true
  image_path_android: assets/images/logo.png
  image_path_ios: assets/images/logo.png
  adapitive_icon_background: assets/images/logo.png
  adaptive_icon_foreground: assets/images/logo.png
